version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/WithoutABotBackend"
    schedule:
      interval: "daily"
      time: "18:00"
    labels:
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/WithoutABotFrontend"
    schedule:
      interval: "daily"
      time: "18:00"
    labels:
      - "dependencies"