version: "3"
services:
  api:
    build:
      context: .
      dockerfile: backend/api/Dockerfile
    ports:
      - "8888:80"
    environment:
      DISCORD_CLIENT_ID: "$COMPOSE_DISCORD_CLIENT_ID"
      DISCORD_CLIENT_SECRET: "$COMPOSE_DISCORD_CLIENT_SECRET"
    depends_on:
      - db
  bot:
    build:
      context: .
      dockerfile: backend/bot/Dockerfile
    environment:
      BOT_TOKEN: "$COMPOSE_BOT_TOKEN"
      TEST_SERVER: "$COMPOSE_TEST_SERVER"
    depends_on:
      - db
  db:
    image: mariadb
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: yes
      MARIADB_DATABASE: withoutabot
      MARIADB_USER: withoutabot
      MARIADB_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      API_URL: "http://api"
    ports:
      - "80:80"
    depends_on:
      - api
volumes:
  db: