[versions]
kordex = "2.3.1-SNAPSHOT"
kordex-gradle = "1.6.1"
kotlin = "2.1.0"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kord-ex = { id = "dev.kordex.gradle.kordex", version.ref = "kordex-gradle" }
