name: WithoutABot CI

on:
  push:
    branches-ignore: [ dependabot/** ]
  pull_request:

jobs:
  testBackend:
    name: Test Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Grant gradlew execute permission
        working-directory: WithoutABotBackend
        run: chmod +x gradlew
      - name: Test with Gradle
        working-directory: WithoutABotBackend
        run: ./gradlew test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./WithoutABotBackend/build/reports/jacoco/test/jacocoTestReport.xml
          flags: unittests